[package]
name = "turtle"
version = "0.1.0"
edition = "2024"

[dependencies]
dirs = "6.0.0"
regex = "1.12.2"
serde = { "version" = "1.0.228", features=["derive"]}
serde_json = "1.0.145"
uuid = "1.18.1"
whoami = "1.6.1"

[[bin]]
name = "turtle"
path = "turtle.rs"
